import js from "@eslint/js";
import tseslint from "typescript-eslint";
import prettier from "eslint-config-prettier";
import globals from "globals";
import { defineConfig, globalIgnores } from "eslint/config";

/**
 * Type-aware linting, on purpose.
 *
 * The rules that earn their place here are the ones a purely syntactic linter cannot express:
 * no-floating-promises and no-misused-promises need the type checker, and in a service that
 * awaits database work on every request an unawaited promise is a silent data bug rather than a
 * style problem. That is worth the slower run.
 *
 * Type-aware rules are scoped to `**\/*.ts` via `extends` rather than applied globally. Applied
 * globally they try to type the plain-JS tooling in scripts/, which belongs to no tsconfig, and
 * the parser fails outright.
 *
 * Formatting is Prettier's job. `eslint-config-prettier` comes last so it can switch off every
 * stylistic rule that would otherwise fight it.
 *
 * Uses ESLint core's `defineConfig` rather than `tseslint.config()`, which is deprecated as of
 * typescript-eslint 8.65 now that core provides the same helper.
 */
export default defineConfig(
  globalIgnores([
    "**/dist/**",
    "**/node_modules/**",
    // Generated by `prisma generate`: never hand-edited, and thousands of lines.
    "packages/db/src/generated/**",
    "**/*.d.ts",
    "**/coverage/**",
  ]),

  // Plain JavaScript: dev tooling and CLI helpers. Syntax rules only, no type information.
  {
    files: ["**/*.{js,mjs,cjs}"],
    extends: [js.configs.recommended],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: globals.node,
    },
  },

  // TypeScript: everything shipped, linted with the type checker.
  {
    files: ["**/*.ts"],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommendedTypeChecked,
      tseslint.configs.stylisticTypeChecked,
    ],
    languageOptions: {
      parserOptions: {
        projectService: {
          // The Prisma config files sit outside any tsconfig `include`, so the project service
          // would refuse to type them. They are build configuration, not shipped code, so
          // resolving them through a default project is fine.
          allowDefaultProject: ["*.config.ts", "packages/*/prisma.*.config.ts"],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // CONTRIBUTING says "no `any` without a comment justifying it". This encodes that: the
      // rule errors, so a deliberate `any` needs an eslint-disable line, and a disable line
      // with no reason next to it is exactly what review should catch.
      "@typescript-eslint/no-explicit-any": "error",

      // A rejected promise nobody awaited is an unhandled rejection, which by default
      // terminates the process. In a multi-tenant service that takes every tenant down with it.
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": "error",

      eqeqeq: ["error", "always"],

      // Underscore-prefixed parameters stay allowed: a positional callback parameter sometimes
      // has to exist only so a later one can be reached.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrors: "none" },
      ],

      // Prefer a narrowing check over an assertion. `!` silences exactly the case that breaks.
      "@typescript-eslint/no-non-null-assertion": "error",
    },
  },

  // Application and library code. Diagnostics belong in a logger, not on stdout: output from a
  // service needs a level and a destination an operator can route.
  {
    files: ["packages/*/src/**/*.ts", "services/*/src/**/*.ts"],
    rules: { "no-console": "error" },
  },

  // CLI entry points and dev tooling. These ARE their own user interface, so writing to stdout
  // is the point rather than an oversight.
  {
    files: ["scripts/**", "packages/*/src/seed/**", "*.config.ts", "packages/*/prisma.*.config.ts"],
    rules: { "no-console": "off" },
  },

  prettier,
);
