import { fileURLToPath } from "node:url";
import { defineConfig } from "vitest/config";

const here = fileURLToPath(new URL(".", import.meta.url));

/**
 * Resolve workspace imports to SOURCE rather than to each package's built `dist`.
 *
 * Without this, a test in services/auth that imports `@compliance-kit/common` loads the compiled
 * output, so the code runs but coverage is attributed to a file the report excludes:
 * packages/common/src showed 0% while its error classes were being constructed on every
 * assertion. Aliasing also means the unit suite does not need a build first.
 */
const workspaceAliases = {
  "@compliance-kit/common": `${here}packages/common/src/index.ts`,
  "@compliance-kit/config": `${here}packages/config/src/index.ts`,
  "@compliance-kit/crypto": `${here}packages/crypto/src/index.ts`,
  "@compliance-kit/db": `${here}packages/db/src/index.ts`,
};

/**
 * Unit tests. The end-to-end proof lives in scripts/smoke-test.sh, which runs the real service
 * against a real Postgres; these cover the logic that is expensive or impossible to reach from
 * the outside, starting with the token codec's negative paths.
 *
 * Tests instantiate classes directly rather than booting a Nest module. Two reasons: it keeps
 * them fast and dependency-free, and esbuild (which Vitest uses to transform TypeScript) does
 * not emit `design:paramtypes` metadata, so container-based DI would not resolve anyway.
 * Anything that genuinely needs the container is integration territory and belongs in the
 * smoke test.
 */
export default defineConfig({
  resolve: { alias: workspaceAliases },
  test: {
    include: ["packages/*/src/**/*.spec.ts", "services/*/src/**/*.spec.ts"],
    environment: "node",
    // Argon2 is deliberately slow (that is the point of a KDF), so a password test can take a
    // few hundred milliseconds. The default 5s is enough, but be explicit about why it is not
    // tightened.
    testTimeout: 15_000,
    coverage: {
      provider: "v8",
      reporter: ["text-summary", "text", "json-summary", "lcov"],
      reportsDirectory: "coverage",
      include: ["packages/*/src/**/*.ts", "services/*/src/**/*.ts"],
      exclude: [
        "**/*.spec.ts",
        // Generated by `prisma generate`.
        "packages/db/src/generated/**",
        // Nest module definitions are declarative wiring with no branches to cover. The smoke
        // test proves they wire up, by booting the application for real.
        "**/*.module.ts",
        "**/main.ts",
        "**/dto/**",
      ],
      /**
       * Thresholds reflect what IS covered, not an aspiration. A threshold the suite cannot meet
       * gets ignored, then disabled, and then the gate is worse than none.
       *
       * The global numbers are low on purpose and are a ratchet: raise them as tests land. They
       * are low because the layers that talk to Postgres are deliberately not unit tested. Their
       * behaviour depends on real database semantics (transactional DDL, unique-violation codes,
       * uuid-vs-text comparison) that a mock would only assert my assumptions about, so they are
       * covered end to end by scripts/smoke-test.sh against a real cluster instead.
       *
       * The per-glob numbers are where the real gate is. They pin the security-critical code at
       * what it currently achieves, so a regression there fails the build even though the global
       * figure would barely move.
       */
      thresholds: {
        lines: 30,
        functions: 30,
        branches: 25,
        statements: 30,

        // The token codec and the password hashing. Fully covered, and must stay that way.
        "packages/crypto/src/**": {
          lines: 100,
          functions: 100,
          statements: 100,
          branches: 100,
        },
        // Domain errors and the wire-contract types. `branches` is 0 because the covered code has
        // no conditionals, not because a branch is untested.
        "packages/common/src/**": {
          lines: 80,
          functions: 70,
          statements: 80,
          branches: 0,
        },
        // Every error the API emits goes through this file.
        "services/auth/src/common/problem-details.filter.ts": {
          lines: 100,
          functions: 100,
          statements: 95,
          branches: 80,
        },
        // The last gate before a handler runs.
        "services/auth/src/rbac/permissions.guard.ts": {
          lines: 100,
          functions: 100,
          statements: 100,
          branches: 80,
        },
      },
    },
  },
});
